variables:
  RELEASE_BRANCH: 'release-0.8'
  PROJECT_SSH: "git@github.lan:${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}.git"
  REMOTE_SSH:  "git@github.com:migashko/${CI_PROJECT_NAME}.git"

stages:
  - build
  - check
  - clean
  - release
  - publish

base-build:
  stage: build
  script:
    - ./.ci/build-and-test.sh g++ 98 Release
    - ./.ci/build-and-test.sh g++ 11 Release
  only:
    - devel
    - tags
    - /^build.*$/

full-build:
  stage: build
  script:
    - ./.ci/build-and-test.sh clang++ 98 Release
    - ./.ci/build-and-test.sh clang++ 11 Release
    - ./.ci/build-and-test.sh g++ 14 Release
    - ./.ci/build-and-test.sh clang++ 14 Release
    - ./.ci/build-and-test.sh g++ 98 Debug
    - ./.ci/build-and-test.sh g++ 11 Debug
    - ./.ci/build-and-test.sh g++ 14 Debug
    - ./.ci/build-and-test.sh clang++ 98 Debug
    - ./.ci/build-and-test.sh clang++ 11 Debug
    - ./.ci/build-and-test.sh clang++ 14 Debug
    - ./.ci/build-and-test.sh g++ 98 Release -DFASLIB_TYPE_LIST_CHECK=ON -DDISABLE_TYPE_LIST_SPEC=ON -DFAS_ALGORITHM_SIMPLIFY=ON -DFAS_ENABLE_WARNINGS=ON
    - ./.ci/build-and-test.sh g++ 11 Release -DFASLIB_TYPE_LIST_CHECK=ON -DDISABLE_TYPE_LIST_SPEC=ON -DFAS_ALGORITHM_SIMPLIFY=ON -DFAS_ENABLE_WARNINGS=ON
    - ./.ci/build-and-test.sh g++ 14 Release -DFASLIB_TYPE_LIST_CHECK=ON -DDISABLE_TYPE_LIST_SPEC=ON -DFAS_ALGORITHM_SIMPLIFY=ON -DFAS_ENABLE_WARNINGS=ON
    - ./.ci/build-and-test.sh clang++ 98 Release -DFASLIB_TYPE_LIST_CHECK=ON -DDISABLE_TYPE_LIST_SPEC=ON -DFAS_ALGORITHM_SIMPLIFY=ON -DFAS_ENABLE_WARNINGS=ON
    - ./.ci/build-and-test.sh clang++ 11 Release -DFASLIB_TYPE_LIST_CHECK=ON -DDISABLE_TYPE_LIST_SPEC=ON -DFAS_ALGORITHM_SIMPLIFY=ON -DFAS_ENABLE_WARNINGS=ON
    - ./.ci/build-and-test.sh clang++ 14 Release -DFASLIB_TYPE_LIST_CHECK=ON -DDISABLE_TYPE_LIST_SPEC=ON -DFAS_ALGORITHM_SIMPLIFY=ON -DFAS_ENABLE_WARNINGS=ON
  only:
    - tags
    - /^build.*$/

cppcheck:
  stage: check
  script:
    - ./.ci/cppcheck.sh --std=c++11
  only:
    - tags
    - /^check.*$/

release-branch:
  stage: release
  script:
    - git push -f ${PROJECT_SSH} ${CI_COMMIT_REF_NAME}:refs/heads/${RELEASE_BRANCH}
  only:
    - tags

make-merge-request:
  stage: release
  script:
    - if [ "${RELEASE_BRANCH}" != "${CI_COMMIT_REF_NAME}" ]; then exit 1; fi
    - HOST=${CI_PROJECT_URL}  CI_PROJECT_ID=${CI_PROJECT_ID} GITLAB_USER_ID=${GITLAB_USER_ID} PRIVATE_TOKEN=${PRIVATE_TOKEN} ./.ci/automr.sh
  only:
    - /^release.*$/

delete-branches:
  stage: clean
  script:
    - git push ${PROJECT_SSH} :${CI_COMMIT_REF_NAME}
  only:
    - /^build.*$/
    - /^check.*$/

faslib-push:
  stage: publish
  only:
    - master
  script:
    - git branch -f mambaru
    - git checkout mambaru
    - git push -f ${REMOTE_SSH} mambaru
    - git push -f --tags ${REMOTE_SSH} mambaru
